#!/usr/bin/env python
import sys
import socket
import json
from termcolor import colored, cprint

server_ip = '127.0.0.1'
server_port = 8838
if len(sys.argv) < 2:
    print('ftlauncher start/stop/restart/status/ls which')
    sys.exit(-1)

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.connect((server_ip, server_port))
try:
    server_cmd = ' '.join(sys.argv[1:]) + '\n'
    server_cmd.encode('utf-8')
    sock.sendall(server_cmd)

    result = b''
    recved = sock.recv(1024)
    while 0 != len(recved):
        result += recved
        recved = sock.recv(1024)

    result.decode('utf-8')
    if 0 != len(result) and '[' == result[0]:
        try:
            jr = json.loads(result)
            step_idx = 0
            for step in jr:
                step_idx += 1
                cprint('Step {0}'.format(step_idx), 'green', attrs=['bold'])
                title_color = 'yellow'
                content_color = 'white'
                cmd = colored(u'command:', title_color)
                cmd += colored(step[u'command'], content_color, attrs=['underline'])
                print(cmd)

                retcode = colored(u'retcode:', title_color)
                retcode += colored(step[u'retcode'], content_color)
                print(retcode)

                cprint(u'output:', title_color)
                output = step[u'message']
                print(output)
        except Exception as e:
            print(result[:-2])
            print(str(e))
    else:
        print(result[:-2])
except Exception as e:
    print('exception ' + str(e))
    sys.exit(-1)
finally:
    sock.close()
