#!/usr/bin/env python
import sys
import socket
import json

server_ip = '127.0.0.1'
server_port = 8838
if len(sys.argv) < 2:
    print('ftlauncher start/stop/restart/status/ls which')
    sys.exit(-1)

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.connect((server_ip, server_port))
try:
    server_cmd = ' '.join(sys.argv[1:]) + '\n'
    print(server_cmd)
    server_cmd.encode('utf-8')
    sock.sendall(server_cmd)

    result = b''
    recved = sock.recv(1024)
    while 0 != len(recved):
        result += recved
        recved = sock.recv(1024)

    result.decode('utf-8')
    jr = json.loads(result)
    print(jr)
except Exception as e:
    print('exception ' + str(e))
    sys.exit(-1)
finally:
    sock.close()
